yblog/urls.py
# coding: utf-8
import os
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'blog.views.index', name='index'),
    url(r'^page/(?P<page>\d+)/', 'blog.views.index', name="page"),
    url(r'^blog/(?P<blogid>\d+)/', 'blog.views.showblog', name="showblog"),
    url(r'^bloglist/(?P<page>\d+)/$', 'blog.views.bloglist', name='bloglist'),
    url(r'^login/$', 'blog.views.login', name='login'),
    url(r'^register/$', 'blog.views.register', name='register'),
    url(r'^change_passwd/$', 'blog.views.change_passwd', name='change_passwd'),
    url(r'^addblog/$', 'blog.views.addblog', name='addblog'),
    url(r'^editblog/(?P<blogid>\d+)/$', 'blog.views.editblog', name='editblog'),
    url(r'^saveblog/$', 'blog.views.saveblog', name='saveblog'),
    url(r'^signout/$', 'blog.views.signout', name='signout'),
    url(r'^help/$', 'blog.views.bloghelp', name='bloghelp'),
    url(r'^markdownblog/$', 'blog.views.markdownblog', name='markdownblog'),
    url(r'^markdownblog/(?P<blogid>\d+)/$', 'blog.views.markdownblog', name='markdownblog'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    #(r'^static/js/(?P<path>.*)$', 'django.views.static.serve', {'document_root': os.path.join(settings.STATIC_ROOT, 'js')}),
    #(r'^static/css/(?P<path>.*)$', 'django.views.static.serve', {'document_root': os.path.join(settings.STATIC_ROOT, 'css')}),
    #(r'^static/img/(?P<path>.*)$', 'django.views.static.serve', {'document_root': os.path.join(settings.STATIC_ROOT, 'img')}),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    #(r'^css/(?P<path>.*)$', 'django.views.static.serve', {'document_root': os.path.join(settings.STATIC_ROOT, 'css')}),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

urlpatterns += staticfiles_urlpatterns() 

blog/models.py
# coding: utf-8

import markdown
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm

# Create your models here.

class Blog(models.Model):
    '''Blog'''
    title = models.CharField(max_length=255, db_index=True, verbose_name=u'标题')
    user = models.ForeignKey(User, verbose_name=u'作者')
    created = models.DateTimeField(auto_now_add=True, verbose_name=u'日期', editable=False, db_index=True)
    markdown = models.TextField(verbose_name=u'内容')
    content = models.TextField(blank=True, null=True, editable=False)
    
    def __unicode__(self):
        return self.title
    
    def save(self):
        self.content = markdown.markdown(self.markdown)
        super(Blog, self).save() # Call the "real" save() method.
        return self
    
    class Meta:
        ordering = ['-created']
        verbose_name_plural = verbose_name = u'Blog'
        
class BlogForm(ModelForm):
    class Meta:
        model = Blog
        #exclude = ("created", "content")
        fields = ('title', 'markdown')

blog/forms.py
# -*- coding: utf-8 -*-
import re
import random
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from wmd.widgets import MarkDownInput
import markdown
from models import Blog

class MarkdownForm(forms.Form):
    blogid = forms.CharField(required=False, widget=forms.HiddenInput())
    title = forms.CharField(label=u'标题', required=True, max_length=50, widget=forms.TextInput(attrs={'tabindex': '1', "class" : "span8"}))
    markdown = forms.CharField(label=u'Markdown', required=True, widget=MarkDownInput(attrs={'tabindex': '2', "class" : "span8", "rows": "20"}))
    
    def clean_title(self):
        title = self.cleaned_data["title"]
        return title
    
    def clean_markdown(self):
        markdown = self.cleaned_data["markdown"]
        return markdown
    
    def save(self, request):
        if not self.is_valid():
            return None
        blogid = self.cleaned_data["blogid"]
        title = self.cleaned_data["title"]
        markdown = self.cleaned_data["markdown"]
        
        if blogid:
            blog = Blog.objects.get(id=int(blogid))
        else:
            blog = Blog()
        blog.title = title
        blog.markdown = markdown
        blog.user = request.user
        blog = blog.save()
        return blog

class SignupForm(forms.Form):
    email = forms.EmailField(label=u'email', required=True, widget=forms.TextInput(attrs={'tabindex': '1', "class" : "span4"}))
    nickname = forms.CharField(label=u'昵称', required=False, max_length=30, widget=forms.TextInput(attrs={'tabindex': '2', "class" : "span4"}))
    password1 = forms.CharField(label=u'密码', required=True, widget=forms.PasswordInput(render_value=False, attrs={'tabindex': '3', "class" : "span4"}))
    password2 = forms.CharField(label=u'重复密码', widget=forms.PasswordInput(render_value=False, attrs={'tabindex': '4', "class" : "span4"}))
    
    def clean_nickname(self):
        nickname = self.cleaned_data['nickname'].strip()
        if nickname and (not re.compile(ur'^[\w|\u2E80-\u9FFF]+$').search(nickname)):
            raise forms.ValidationError(u'昵称“%s”名非法，昵称目前仅允许使用中英文字数字和下划线' % nickname)
        return nickname
    
    def clean_email(self):
        email = self.cleaned_data["email"].strip().lower()
        try:
            # 每个Member对应一个User，但是允许后台User不对应Member
            User.objects.get(username__iexact=email) 
        except User.DoesNotExist:
            return email
        raise forms.ValidationError(u'已经有用户使用“%s”注册了用户，请您确认邮件是否拼写错误' % email)
        return email
    
    def clean_password1(self):
        password = self.cleaned_data['password1'].strip()
        if not password:
            raise forms.ValidationError(u'对不起，密码不能为空')
        return password
    
    def clean(self):
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(u'您所输入的两个密码不一致，请您重新输入')
        return self.cleaned_data
    
    def save(self, request):
        if not self.is_valid():
            return False
        email = self.cleaned_data['email']
        nickname = self.cleaned_data['nickname']
        password = self.cleaned_data['password1']
        
        user = User()
        user.username = email
        user.email = email
        user.set_password(password)
        user.is_active = True
        user.save()
        #注册后登录
        credential = { 'username': email, 'password': password}
        user = authenticate(**credential)
        login(request, user)
        return True
    
class LoginForm(forms.Form):
    email = forms.EmailField(label=u'email', required=True, widget=forms.TextInput(attrs={'tabindex': '1'}))
    password = forms.CharField(label=u'密码', required=True, widget=forms.PasswordInput(render_value=False, attrs={'tabindex': '2'}))
    remember = forms.BooleanField(label=u'记住登陆信息', help_text=u'如果选择记住登陆信息，会保留登陆信息2周', required = False, widget=forms.CheckboxInput(attrs={'tabindex': '3'}))
    
    user = None
    
    def clean_email(self):
        email=self.cleaned_data.get('email','')
        return email
    
    def clean(self):
        super(LoginForm,self).clean()
        credential = { 'username': self.cleaned_data.get('email',''), 'password': self.cleaned_data.get('password','')}
        user = authenticate(**credential)
        if user:
            if user.is_active:
                self.user = user
            else:
                raise forms.ValidationError(u'您还没有通过邮件激活帐号，请您登陆邮箱打开链接激活')
        else:
            raise forms.ValidationError(u'您输入的邮件地址与密码不匹配或者帐号还不存在，请您重试或者注册帐号')
        return self.cleaned_data

    def login(self, request):
        if self.is_valid():
            login(request, self.user)
            if "remember" in self.cleaned_data and self.cleaned_data["remember"]:
                request.session.set_expiry(60 * 60 * 24 * 7 * 3)
            else:
                request.session.set_expiry(0)
            return True
        return False

class ChangePasswdForm(forms.Form):
    oldpassword = forms.CharField(label=u'原密码', required=True, widget=forms.PasswordInput(render_value=False, attrs={'tabindex': '1'}))
    password1 = forms.CharField(label=u'新密码', required=True, widget=forms.PasswordInput(render_value=False, attrs={'tabindex': '2'}))
    password2 = forms.CharField(label=u'重复新密码', required=True, widget=forms.PasswordInput(render_value=False, attrs={'tabindex': '3'}))
   
    def __init__(self, user=None, *args, **kwargs):
        self.user = user
        super(ChangePasswdForm, self).__init__(*args, **kwargs)
    
    def clean_oldpassword(self):
        if not self.user.check_password(self.cleaned_data.get("oldpassword")):
            raise forms.ValidationError(u"旧密码不正确，请重试")
        return self.cleaned_data["oldpassword"]

    def clean_password1(self):
        password = self.cleaned_data['password1'].strip()
        if not password:
            raise forms.ValidationError(u'密码不能为空')
        return password

    def clean(self):
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(u'您所输入的两个密码不一致，请您重新输入')
        return self.cleaned_data

    def save(self):
        if not self.is_valid():
            return False
        password = self.cleaned_data['password1']
        self.user.set_password(password)
        self.user.save()
        return True

blog/views.py
# Create your views here.

from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.conf import settings
from django.core.urlresolvers import reverse
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.views.decorators.csrf import csrf_protect
from django.utils.translation import ugettext_lazy as _
from django.utils.html import escapejs
from django.contrib.auth import login, authenticate
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator,InvalidPage,EmptyPage,PageNotAnInteger
from models import Blog, BlogForm
from forms import SignupForm, LoginForm,MarkdownForm, ChangePasswdForm
import markdown
import time
BLOGS_PER_PAGE = 5
BLOGS_PER_LISTPAGE = 10

def get_page(objs, page):
    paginator = Paginator(objs, BLOGS_PER_PAGE)
    
    try:
        ret = paginator.page(page)
    except (EmptyPage, InvalidPage):
        ret = paginator.page(paginator.num_pages)

    return ret

def index(req, page=1):
    try:
        page = int(page)
    except ValueError:
        page = 1
    
    blogs = get_page(Blog.objects.all(), page)
    return render_to_response('index.html', {'settings' : settings, 'blogs' : blogs}, context_instance=RequestContext(req))

def addblog(req):
    blog = Blog()
    blog.user = req.user
    form = BlogForm(instance=blog)
    return render_to_response('post.html', {'settings' : settings, 'form' : form}, context_instance=RequestContext(req))
    
def editblog(req, blogid):
    blog = Blog.objects.get(id=blogid)
    if blog.user != req.user:
        return HttpResponseRedirect('/')
    form = BlogForm(instance=blog)
    return render_to_response('post.html', {'settings' : settings, 'form' : form}, context_instance=RequestContext(req))

def saveblog(req):
    form = BlogForm(req.POST)
    blog = form.save(commit=False)
    blog.user = req.user
    #blog.content = markdown.markdown(blog.markdown)
    blog.save()
    #return index(req)
    return HttpResponseRedirect(reverse('showblog', args=[blog.id]))
    
def showblog(req, blogid):
    blogid = int(blogid)
    blog = Blog.objects.select_related().get(id=blogid)
    return render_to_response('blog.html', {'settings' : settings, 'blog' : blog}, context_instance=RequestContext(req))

def bloglist(req, page=1):
    blogs = Blog.objects.all()
    paginator = Paginator(blogs, BLOGS_PER_LISTPAGE)
    
    try:
        blogs = paginator.page(page)
    except (EmptyPage, InvalidPage):
        blogs = paginator.page(paginator.num_pages)
    return render_to_response('bloglist.html', {'settings' : settings, 'blogs' : blogs}, context_instance=RequestContext(req))

def login(req):
    if req.method == 'POST':
        form = LoginForm(req.POST)
        if form.login(req):
            return HttpResponseRedirect(reverse('index', args=[]))
    else:
        form = LoginForm()
    return render_to_response('login.html', {'settings' : settings, 'form': form}, context_instance=RequestContext(req))

def change_passwd(req):
    if req.method == 'POST' and req.user.is_authenticated():
        form = ChangePasswdForm(req.user, req.POST)
        if form.save():
            return render_to_response('change_passwd_success.html', {'settings' : settings}, context_instance=RequestContext(req))
    else:
        form = ChangePasswdForm(req.user)
    return render_to_response('change_passwd.html', {'settings' : settings, 'form': form}, context_instance=RequestContext(req))

def register(req):
    if req.method == 'POST':
        form = SignupForm(req.POST)
        if form.save(req):
            ctx = {'settings' : settings, 'email': form.cleaned_data['email'], }
            return render_to_response('singup_success.html', ctx, context_instance=RequestContext(req))
    else:
        form = SignupForm()
    return render_to_response('singup.html', {'settings' : settings, 'form': form}, context_instance=RequestContext(req))

def signout(request):
    auth_logout(request)
    return HttpResponseRedirect('/')

def bloghelp(req):
    return HttpResponseRedirect(reverse('index', args=[]))

def markdownblog(req, blogid=None):
    if req.method == 'POST':
        form = MarkdownForm(req.POST)
        blog = form.save(req)
        if blog:
            return HttpResponseRedirect(reverse('showblog', args=[blog.id]))
    else:
        if blogid:
            blog = Blog.objects.get(id=blogid)
            blogid = blog.id
            title = blog.title
            markdown = blog.markdown
            form = MarkdownForm({'blogid' : blog.id, 'title' : blog.title, 'markdown' : blog.markdown})
        else:
            form = MarkdownForm()
            
    return render_to_response('markdown.html', {'settings': settings, 'form': form}, context_instance=RequestContext(req))



templates/base.html
<!DOCTYPE html>{% load i18n %}
<html lang="zh-CN">
    <head>
        <meta charset="utf-8" />
        <title>{% block title %}{% endblock %}{% trans '博客' %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="{{ settings.STATIC_URL }}css/bootstrap.css" rel="stylesheet">
        <link href="{{ settings.STATIC_URL }}css/bootstrap-responsive.css" rel="stylesheet">
        <!--[if lt IE 9]>
            <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        {% block css %}{% endblock %}
        <link rel="shortcut icon" type="image/x-icon" href="{{ settings.STATIC_URL }}favicon.ico" />
    </head>
    <body data-spy="scroll" data-target=".subnav">
        <!-- Navbar ================================================== -->
        <div class="header navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                     <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                     </a>
                    <a class="brand" href="{{ settings.SITE_PREFIX }}/">{% trans '博客' %}</a>
                    <div class="nav-collapse">
                    <ul class="nav nav-pills">
                        <li class="index {% block index-menu %}{% endblock %}"><a href="{{ settings.SITE_PREFIX }}/">{% trans '首页' %}</a></li>
                        <li class="list {% block list-menu %}{% endblock %}"><a href="{{ settings.SITE_PREFIX }}/bloglist/1/">{% trans '目录' %}</a></li>
                        {% if not user.is_authenticated %}
                        <li class="login {% block login-menu %}{% endblock %}"><a href="{{ settings.SITE_PREFIX }}/login/">{% trans '登录' %}</a></li>
                        <li class="register {% block register-menu %}{% endblock %}"><a href="{{ settings.SITE_PREFIX }}/register/">{% trans '注册' %}</a></li>
                        {% else %}
                        <li class="markdownblog {% block addblog-menu %}{% endblock %}"><a href="{{ settings.SITE_PREFIX }}/markdownblog/">{% trans '新增' %}</a></li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" ><b>{{ user.username }}</b><b class="caret"></b></a>
                            <ul class="dropdown-menu pull-right" role="menu" aria-labelledby="dropdownMenu">
                              <li><a href="{{ settings.SITE_PREFIX }}/change_passwd/">{% trans '修改密码' %}</a></li>
                              <li class="divider"></li>
                              <li><a href="{{ settings.SITE_PREFIX }}/signout/">{% trans '退出' %}</a></li>
                            </ul>
                        </li>
                        {% endif %}
                    </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        
        <!-- Container ================================================== -->
        <div class="clear">&nbsp;</div>
        <div class="clear">&nbsp;</div>
        <br/><br/><br/>
        <div class="container" >
            <div class="row">
            <div class="span8 offset1" >
            <!-- content ================================================== -->
            {% block content %}{% endblock %}
            </div>
            <div class="span2 offset1">
            <!-- sidebar ================================================== -->
            {% block sidebar %}
                <div class="well sidebar-nav">
                    <ul class="nav nav-list">
                        <li class="nav-header">About Me</li>
                        <li>{{ user.username }}</li>
                        <li class="nav-header">Links</li>
                        <li>link1</li>
                        <li>link2</li>
                        <li>link3</li>
                    </ul>
                </div>
            {% endblock %}
            </div>
            </div>
            
            <!-- Footer ================================================== -->
            <div class="divider">&nbsp;</div>
            <div class="clear">&nbsp;</div>
            <br/><br/><br/>
            <footer class="footer">
                <div class="container">
                    <div class="page-header">
                    </div>
                    <div class="row">
                    <p class="span4 offset2">&copy; Company 2012</p> 
                    <p class="span2 offset2 pull-right"><a href="#">回到顶端</a></p>
                    </div>
                </div>
            </footer>
          
        </div><!-- /container -->
        
        <script src="{{ settings.STATIC_URL }}js/jquery.min.js"></script>
        <script src="{{ settings.STATIC_URL }}js/bootstrap.js"></script>
        {% block js %}{% endblock %}
    </body>
</html>

templates/blog.html
{% extends 'base.html' %}
{% load i18n %}

{% block css %}
{% endblock %}

{% block title %}{% trans '首页' %} - {% endblock %}

{% block js %}
{% endblock %}

{% block content %}
	<section id="blog{{ blog.id }}" class="row well" >
		<div class="page-header">
			<h1><a href="{{ settings.SITE_PREFIX }}/blog/{{ blog.id }}/">{{ blog.title }}</a> </h1>
			<h1>
			<small>{% trans '时间' %}: {{ blog.created|date:"Y-m-d H:i:s" }}</small>
			<small>{% trans '作者' %} : {{ blog.user }} </small>
		{% if user and user.is_authenticated and user == blog.user %}
		<span class="pull-right">
			<a class="btn" href="{{ settings.SITE_PREFIX }}/markdownblog/{{ blog.id }}/">{% trans '编辑' %}</a>
			<a class="btn" href="{{ settings.SITE_PREFIX }}/deleteblog/{{ blog.id }}/">{% trans '删除' %}</a>
		</span>
		{% endif %}
		</h1>
		</div>
		<div class="page-content">
			<div>
			{{ blog.content|safe }}
			</div>
		</div>
	</section>
{% endblock %}



templates/bloglist.html
{% extends 'base.html' %}
{% load i18n %}

{% block css %}
{% endblock %}

{% block index-menu %}active{% endblock %}

{% block title %}{% trans '列表' %} - {% endblock %}

{% block js %}
{% endblock %}

{% block content %}
    <div class="well" >
{% for blog in blogs %}
    
        <div class="row">
            <a class="span4" href="{{ settings.SITE_PREFIX }}/blog/{{ blog.id }}/">{{ blog.title }}</a> 
            <small class="span2">{% trans '时间' %}: {{ blog.created|date:"Y-m-d H:i:s" }}</small>
            <small>{% trans '作者' %} : {{ blog.user }} </small>
        </div>
{% endfor %}
    </div>

    <div class="pagination pull-right">
        <ul class="pager">
        {% if blogs.has_previous %}
        <li>
            <a class="btn-small" href="{{ settings.SITE_PREFIX }}/bloglist/{{ blogs.previous_page_number }}/">{% trans '上一页' %}</a>
         </li>
        {% endif %}
        
        {% if blogs.has_next %}
        <li>
            <a class="btn-small" href="{{ settings.SITE_PREFIX }}/bloglist/{{ blogs.next_page_number }}/">{% trans '下一页' %}</a>
        </li>
        {% endif %}
        
        </ul>
    </div>
{% endblock %}



templates/change_passwd.html
{% extends 'base.html' %}
{% load i18n %}

{% block css %}
{% endblock %}

{% block index-menu %}active{% endblock %}

{% block title %}{% trans '修改密码' %} - {% endblock %}

{% block js %}
{% endblock %}

{% block content %}
<form action="" method="post"> {% csrf_token %}
    {{ form.as_p }}
    {{ form.non_field_errors }}
    
   <p class="row pull-right"><input type="submit" class="btn btn-primary" value="{% trans '确定' %}" />  <a href="{{ settings.SITE_PREFIX }}/" class="btn" >{% trans '取消' %}</a>
   </p>
</form>
{% endblock %}

templates/change_passwd_success.html
{% extends "base.html" %}
{% block title %} - 密码修改成功{% endblock %}
{% block content %}
  <div id="notice" class="narrow">
    <p>{{ email }}</p>
    <p>你的密码修改成功。</p>
    <p>点击<a href="{{ settings.SITE_PREFIX }}/" >这里</a> 返回首页。</p>
  </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load i18n %}

{% block css %}
{% endblock %}

{% block index-menu %}active{% endblock %}

{% block title %}{% trans '首页' %} - {% endblock %}

{% block js %}
{% endblock %}

{% block content %}
{% for blog in blogs %}
	<section id="blog{{ blog.id }}" class="row well" >
		<div class="page-header">
			<h1><a href="{{ settings.SITE_PREFIX }}/blog/{{ blog.id }}/">{{ blog.title }}</a> </h1>
			<h1>
			<small>{% trans '时间' %}: {{ blog.created|date:"Y-m-d H:i:s" }}</small>
			<small>{% trans '作者' %} : {{ blog.user }} </small></h1>
		</div>
		<div class="page-content">
			<div>
			{{ blog.content|safe }}
			</div>
		</div>
	</section>
{% endfor %}

	<div class="pagination pull-right">
		<ul class="pager">
		{% if blogs.has_previous %}
		<li>
			<a class="btn-small" href="{{ settings.SITE_PREFIX }}/page/{{ blogs.previous_page_number }}/">{% trans '上一页' %}</a>
		 </li>
		{% endif %}
		
		{% if blogs.has_next %}
		<li>
			<a class="btn-small" href="{{ settings.SITE_PREFIX }}/page/{{ blogs.next_page_number }}/">{% trans '下一页' %}</a>
		</li>
		{% endif %}
		  
		
		</ul>
	</div>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %} - 登录{% endblock %}
{% block content %}
  <div id="login" class="narrow">
    <form action="" method="post">
      {% csrf_token %}
      <p>
        {{ form.email.errors }}
        <label>{{ form.email.label }}</label>
        {{ form.email }}
        <span class="hint"></span>
      </p>
      <p>
        {{ form.password.errors }}
        <label>{{ form.password.label }}</label>
        {{ form.password }}
      </p>
      <span class="hint"></span>
      <p>
        {{ form.remember.errors }}
        {{ form.remember }} <label style="display:inline">{{ form.remember.label }}</label>
        
      </p>
      <span class="hint"></span>
      {{ form.non_field_errors }}
      <input type="text" name="captcha" style="display:none">
      <input type="submit" class="btn btn-primary" value="登录" tabindex="3"/>
      <a href="{{ settings.SITE_PREFIX }}/" class="btn" tabindex="4">取消</a>
    </form>
  </div>
{% endblock %}

templates/markdown.html
{% extends 'base.html' %}
{% load i18n %}

{% block css %}
{% endblock %}

{% block index-menu %}active{% endblock %}

{% block title %}{% trans '编辑' %} - {% endblock %}

{% block js %}
{{ form.media }}
{% endblock %}

{% block content %}
<form action="" method="post"> {% csrf_token %}
    {{ form.as_p }}
    {{ form.non_field_errors }}
    
   <p class="row pull-right"><input type="submit" class="btn btn-primary" value="{% trans '保存' %}" />  <a href="{{ settings.SITE_PREFIX }}/" class="btn" >{% trans '取消' %}</a>
   </p>
</form>
{% endblock %}

templates/post.html
{% extends 'base.html' %}
{% load i18n %}

{% block css %}
{% endblock %}

{% block index-menu %}active{% endblock %}

{% block title %}{% trans '编辑' %} - {% endblock %}

{% block js %}
{% endblock %}

{% block content %}
<form action="/saveblog/" method="post"> {% csrf_token %}
	<input type="hidden" name="user" id="id_user" value="{{ user }}" />
	<div class="row">
		<div class="span8" >
        <label for="id_title">{% trans '标题' %}</label> <input class="span8" id="id_title" type="text" name="title" maxlength="255" value="{{ form.title.value }}"/>
		</div>
    </div>
    
    <div class="row">
		<div class="span8" >
         <label for="id_markdown">{% trans 'Markdown' %}</label> <textarea class="span8" id="id_markdown" rows="20" name="markdown" >{{ form.markdown.value }}</textarea>
		 </div>
    </div>
	
	
   <p class="row pull-right"><input type="submit" class="btn btn-primary" value="{% trans '保存' %}" />  <a href="{{ settings.SITE_PREFIX }}/" class="btn" >{% trans '取消' %}</a>
   </p>
</form>
{% endblock %}

templates/singup_success.html
{% extends "base.html" %}
{% block title %} - 注册成功{% endblock %}
{% block content %}
  <div id="notice" class="narrow">
    <p>恭喜你注册成功。注册邮箱: {{ email }}</p>
    <p>点击<a href="{{ settings.SITE_PREFIX }}/" >这里</a> 返回首页。</p>
  </div>
{% endblock %}